Allow private or public claims to be parsed as Json objects
jwt-scala/jwt-scala pull request #84
Opened 2018-03-07 03:24 UTC by evbo

A common use-case of Jwt-Scala (and JWT at large) is developing so-called "public" or "private" claims and or header params.  These are functionally no different than "reserved" claims/header params, other than that they have no standard definition and may only be distinguished within your network or niche industry. "issuer", "subject", "audience" etc. are all examples of reserved claims, whereas "username" is a fairly common example of a non-reserved claim. 

Given that there may be many of these public/private claims, it would save a lot of boilerplate code not having to parse them separate from how reserved claims are parsed. In other words, it makes sense to either extend or compose with reserved jwt claims/header params, so that you can customize for your public or private network's needs. 

Here is an example where reserved headers along with a private username claim is used:

```
// define your network-specific claims, and compose them with the usual reservedClaims
case class JwtPrivateClaim(user: Option[String] = None, reservedClaims: JwtClaim = JwtClaim()) {

// merge your json definition along with the reserved claims too
  def toJson: String = JwtUtils.mergeJson(JwtUtils.hashToJson(Seq(
      "user" -> user,
    ).collect {
    case (key, Some(value)) => (key -> value)
    }), reservedClaims.toJson)
}

// create a parser with claim type set to the one you just defined
case object JwtJson4sPrivate extends JwtJson4sParser[JwtHeader, JwtPrivateClaim] {
  override protected def parseClaim(claim: String): JwtPrivateClaim = {
    val claimJson = parse(claim)
    val jwtReservedClaim: JwtClaim = readClaim(claimJson)
    val content = parse(jwtReservedClaim.content)
    JwtPrivateClaim(extractString(content, "user"), jwtReservedClaim.copy(content = "{}"))
  }

// here is the only boilerplate (if you don't have private header params too):
  override protected def parseHeader(header: String): JwtHeader = readHeader(parse(header))

// marginal boilerplate as well I suppose
  override protected def extractExpiration(claim: JwtPrivateClaim): Option[Long] = claim.reservedClaims.expiration
  override protected def extractNotBefore(claim: JwtPrivateClaim): Option[Long] = claim.reservedClaims.notBefore
}

// here is how you marshal your claims:
trait JsonSupport extends SprayJsonSupport with DefaultJsonProtocol {
  implicit val jwtReservedClaimFormat = jsonFormat8(JwtClaim)
  implicit val jwtPrivateClaimFormat = jsonFormat2(JwtPrivateClaim)
}
```

you can then use the decodeAll method as before, now with your fully objectified claims:

```
val decoded: Try[(JwtHeader, JwtPrivateClaim, String)] = JwtJson4sPrivate.decodeAll(token)
```

This PR only changes modifiers and type generics, no functional code change was made and unit tests all pass still.

2018-03-07 09:59 UTC, pauldijou requested changes
~~Did you manage to run the tests in the end?~~ You did 👍 

Why are you using `case object` rather than just `object`?

Otherwise, seems pretty good.

2018-03-07 09:59 UTC, pauldijou commented on build.sbt
> +val buildVersion = "0.16.1"
If merger, this will be `0.17.0`, you also need to update `previousVersion`.

2018-03-07 09:59 UTC, pauldijou commented on json/circe/src/main/scala/JwtCirce.scala
> +      algorithm = getAlg(cursor)
Indentation

2018-03-07 09:59 UTC, pauldijou commented on json/circe/src/main/scala/JwtCirce.scala
> +      content = contentCursor.top.asJson.noSpaces
Indentation

2018-03-07 09:59 UTC, pauldijou commented on json/json4s-native/src/main/scala/JwtJson4sNative.scala
> +}
New line

2018-03-07 09:59 UTC, pauldijou commented on json/upickle/src/main/scala/JwtUpickle.scala
> +}
New line

2018-03-07 12:25 UTC, evbo commented
The benefits to using case object instead of object are very slim, if hardly there at all. I can just use object, but in case you're curious here's a breakdown of the differences: https://stackoverflow.com/a/5271730/1080804

I'll make the other corrections as well. Thanks!

2018-03-07 14:08 UTC, pauldijou approved these changes

2018-03-07 14:15 UTC, pauldijou commented
Do you think you could write a bit of doc about it? Like how it works basically and an example on how to create your own custom header/claim. Best way to do that would be to write a `tut` markdown file. You can put it [with all others](https://github.com/pauldijou/jwt-scala/tree/master/docs/src/main/tut/_includes/tut). Also, add it [as a sample](https://github.com/pauldijou/jwt-scala/tree/master/docs/src/site/samples). Run `docs/tut` to test if it compiles, don't bother testing the website, I will add a link to it after merging.

2018-03-08 21:05 UTC, evbo commented
I committed the docs yesterday - sorry forgot to leave a comment about it. Let me know if there's anything else you need to merge.

2018-03-10 02:07 UTC, evbo commented
@pauldijou are we good to merge?

2018-03-10 11:25 UTC, merged

2018-03-10 12:02 UTC, pauldijou commented
I did merge it but wanted to understand better. Is the goal just to add custom fields to the `JwtClaim`? Because you could already do that **before** this PR right? Check the [play-json](http://pauldijou.fr/jwt-scala/samples/jwt-play-json/) sample, it shows how to add a `user` custom field.

So, I don't really want the markdown documentation to focus on that. You should just use the normal claim for such purpose. Is there any other benefit for this code?

2018-03-10 13:51 UTC, evbo commented
Not only are you 100% right, but the code is actually simpler if you just parse the `content` param rather than having to implement all the boilerplate my PR was proposing.

Whoops, complete oversight on my part. Sorry, but I think this merge should be reverted.

Here's a much cleaner approach to take now that I better understand:

```
import org.json4s._
import org.json42.jackson.JsonMethods.parse

case class JwtPrivateClaim(user: Option[String] = None)

parse(JwtJson4s.decodeAll(token, JwtOptions(signature = false))._2.content)
    .extract[JwtPrivateClaim]
```